#pragma kernel EvolveSpectrum

float Time; // simulation time

// pass noise texture for random numbers
Texture2D<float4> h0Tex; // RG: real, imag components of h0, BA: real, imag components of h0(-k)
Texture2D<float4> WaveTex; // RG: real, imag components of h(k,t), BA: real, imag components of h(-k,t)
RWTexture2D<float4> HeightMap; // packed complex components of Dy and pDx/pz
RWTexture2D<float4> NormalMap; // packed complex components of Dy and pDx/pz
// RWTexture2D<float4> Dx_Dz; // packed complex components of Dx and Dz
// RWTexture2D<float4> Dyx_Dyz; // packed complex components of pDy/px and pDy/pz
// RWTexture2D<float4> Dxx_Dzz; // packed complex components of pDx/px and pDz/pz

float2 Euler(float x)
{
    return float2(cos(x), sin(x));
}

float2 ComplexMul(float2 a, float2 b)
{
    return float2(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x);
}

[numthreads(8,8,1)]
void EvolveSpectrum(uint3 id : SV_DispatchThreadID)
{
    uint W, H;
    h0Tex.GetDimensions(W, H);
    if (id.x >= W || id.y >= H) return;

    // fetch h0 and h0(-k)
    float2 h0 = h0Tex[id.xy].xy;
    float2 h0_minusk = h0Tex[id.xy].zw; 
    float4 wave = WaveTex[id.xy];
    float dispersion = wave.w;

    float phase = dispersion * Time;
    float2 exponent = Euler(phase);

    float2 h = ComplexMul(h0, exponent) + ComplexMul(h0_minusk, float2(exponent.x, -exponent.y));

    float2 ih = float2(-h.y, h.x); // i * h(k, t)

    float2 k = wave.xy;
    // float kLengthNormFactor = 1 / wave.z;

    float2 tangent = k.x * ih;
    float2 bitangent = k.y * ih;

    // compute displacement components in frequency domain -> Dx, Dy, Dz
    // float2 Dx = ih * wave.x * kLengthNormFactor; // i * h(k, t) * (kx / |k|)
    // Dy = h // vertical displacement is just h(k, t) 
    // float2 Dz = ih * wave.z * kLengthNormFactor; // i * h(k, t) * (kz / |k|) 

    // float2 pDx_px = -h*wave.x * wave.x * kLengthNormFactor; // i * i * h(k, t) * (kx^2 / |k|)
    // float2 pDy_px = ih*wave.x; // i * h(k, t) * (kx)
    
    // float2 pDx_pz = -h*wave.x * wave.z * kLengthNormFactor; // i * i * h(k, t) * (kx*kz / |k|)
    // float2 pDy_pz = ih*wave.z; // i * h(k, t) * (kz)
    // float2 pDz_pz = -h*wave.z * wave.z * kLengthNormFactor; // i * i * h(k, t) * (kz^2 / |k|)

    HeightMap[id.xy] = float4(h, 0, 1);
    NormalMap[id.xy] = float4(tangent.x, 0, bitangent.x, 0);
    // Dx_Dz[id.xy] = float4(Dx, Dz);
    // Dyx_Dyz[id.xy] = float4(pDy_px, pDy_pz);
    // Dxx_Dzz[id.xy] = float4(pDx_px, pDz_pz);
}
